### ISSUE TITLE
Possibly wrong url in pom

### ISSUE THREAD

**Issue by andreacalia** [shadskii/ReactorFX#2]
Hi
Just to let you know, this points to another project, in case this is not intended to be :)

https://github.com/shadskii/ReactorFX/blob/6758501cce4ea7c794ab1391c7f0706d0c3e5f15/build.gradle#L48

**Comment by shadskii** [comment]
Yes, great catch! To upload this to maven I used a walkthrough with a sample gradle upload script. It seems that I forgot to change the url. I've updated it to a more appropriate url. I will upload the updated pom to maven soon.

Thanks for letting me know!
