### ISSUE TITLE
discution

### ISSUE THREAD

**Issue by halimpuckjava** [shadskii/ReactorFX#3]
hi 

i have a simple senaio: i have a loop with (1000 iteration) and just i want to launch this loop aync, son i use jfxdialog, i launch this senaio in Task, onrunning event i show my jfxdialog and onsuccess or onfaild i close it, i see that jfxdialog is show after loop terminate !!! however i show it in onrunning event (normaly it show before loop start) , any explanation please

**Comment by shadskii** [comment]
Hi!

I will be better able to assist you if you can provide me with the code in question. Can you provide a minimal, complete, and verifiable example? See this [stackoverflow page](https://stackoverflow.com/help/mcve) for what I'm talking about. 

Thanks!

Jake

**Comment by halimpuckjava** [comment]
hi

this is a sample code (in kotlin) to explain my idea

var task = object : Task<Unit>() {
            override fun call() {
                (1..10000).forEach { println("i: $it") }
            }
        }
        task.setOnRunning { showdialog }
        task.setOnFailed { closedialog }
        task.setOnSucceeded { closedialog }
        
        thread{
            task
        }

so i expected to show jfxdialog before loop start (onrunning) and it close after loop terminate (onsucess) or faild (onfailed), in real execution my jfxdialog appear after loop terminate and it close in same time, i think that the time of showing dialog is more then time for loop, if my idea is correct how to fix this senario
